use_frameworks!

platform :ios, '9.0'

target 'KoreanStringSearchHelper_Example' do
  pod 'KoreanStringSearchHelper', :path => '../'

  target 'KoreanStringSearchHelper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
